update the workflow

diff --git a/.github/workflows/test-adapters.yml b/.github/workflows/test-adapters.yml
--- a/.github/workflows/test-adapters.yml
+++ b/.github/workflows/test-adapters.yml
@@ -39,7 +39,19 @@ jobs:
         run: pip install PyYAML
       - id: get-changes
         run: |
-          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            BASE_SHA=${{ github.event.pull_request.base.sha }}
+            HEAD_SHA=${{ github.event.pull_request.head.sha }}
+          else
+            BASE_SHA=${{ github.event.before }}
+            HEAD_SHA=${{ github.sha }}
+          fi
+          
+          if ! CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA); then
+            echo "Error: Unable to determine changed files. Using all files instead."
+            CHANGED_FILES=$(git ls-files)
+          fi
+          
           echo "Changed files:"
           echo "$CHANGED_FILES"
           ADAPTERS=$(echo "$CHANGED_FILES" | grep -oP 'biocypher_metta/adapters/\K[^/]+(?=_adapter\.py)' | sort -u | tr '\n' ',' | sed 's/,$//')
